const items = {
    // weapons
    sword: {
        name: "Sword",
        type: "weapon",
        damage: 10,
        attackSpeed: 1,
        range: 1,
        CritChance: 0,
        CritDamage: 1.5,
    },
    dagger: {
        name: "Dagger",
        type: "weapon",
        damage: 5,
        attackSpeed: 2,
        range: 1,
        CritChance: 0,
        CritDamage: 1.5,
    },
    bow: {
        name: "Bow",
        type: "weapon",
        damage: 15,
        attackSpeed: 1,
        range: 5,
        CritChance: 0,
        CritDamage: 1.5,
    },
    staff: {
        name: "Staff",
        type: "weapon",
        damage: 20,
        attackSpeed: 1.5,
        range: 8,
        CritChance: 0,
        CritDamage: 1.5,
    },
    // armor
    leatherArmor: {
        name: "Leather Armor",
        type: "armor",
        defense: 5,
        HPRegeneration: 0,
        lifeSteal: 0,
    },
    chainMail: {
        name: "Chain Mail",
        type: "armor",
        defense: 10,
        HPRegeneration: 0,
        lifeSteal: 0,
    },
    plateArmor: {
        name: "Plate Armor",
        type: "armor",
        defense: 20,
        HPRegeneration: 0,
        lifeSteal: 0,
    },
    // accessories
    ringOfHealth: {
        name: "Ring of Health",
        type: "accessory",
        defense: 0,
        HPRegeneration: 5,
        lifeSteal: 0,
    },
    ringOfLifeSteal: {
        name: "Ring of Life Steal",
        type: "accessory",
        defense: 0,
        HPRegeneration: 0,
        lifeSteal: 5,
    },
    ringOfDefense: {
        name: "Ring of Defense",
        type: "accessory",
        defense: 5,
        HPRegeneration: 0,
        lifeSteal: 0,
    },
    ringOfAttackSpeed: {
        name: "Ring of Attack Speed",
        type: "accessory",
        defense: 0,
        HPRegeneration: 0,
        lifeSteal: 0,
        attackSpeed: 0.1,
    },
    ringOfCritChance: {
        name: "Ring of Crit Chance",
        type: "accessory",
        defense: 0,
        HPRegeneration: 0,
        lifeSteal: 0,
        CritChance: 0.1,
    },
    ringOfCritDamage: {
        name: "Ring of Crit Damage",
        type: "accessory",
        defense: 0,
        HPRegeneration: 0,
        lifeSteal: 0,
        CritDamage: 0.1,
    },
    // potions
    healthPotion: {
        name: "Health Potion",
        type: "potion",
        health: 50,
    },
    // other
    gold: {
        name: "Gold",
        type: "other",
        gold: 1,
    },
};